### ISSUE TITLE
Lovely feature ♥️♥️♥️

### ISSUE THREAD

**Issue by miumfv** [quanle51297/spotimiu#9]
### Is your feature request related to a problem? Please describe.
 Miss Quan Quan

### Describe the solution you'd like
 Give me a kiss when I miss Quan Quan

### Describe alternatives you've considered
 Give me a voice message when I miss Quan Quan

### Additional context
 Thơm thơm~~~

**Comment by quanle51297** [comment]
@miumfv 
Would you like to create a button and send a voice message when clicking it?

**Comment by miumfv** [comment]
Absolutely ~~~ Make me a cute button to click @quanle51297 😊

**Comment by quanle51297** [comment]
@miumfv 
Roger That!

**Comment by quanle51297** [comment]
@miumfv

I've added a button.
Please help me check it.
